### ISSUE TITLE
Build, run envirovnment

### ISSUE THREAD

**Issue by paloliska** [ossf/criticality_score#16] opened 2020-12-11 08:54 UTC
This criticality does not take into account build and run environment dependencies.

For example, for java project, there is dependency on maven or gradle, and on jdk.

**Comment by inferno-chromium** [comment] 2020-12-11 13:29
Duplicate of https://github.com/ossf/criticality_score/issues/8, this is hard problem and we are looking for ideas here. How do you want to change criticality score based on dependencies, please add ideas in that bug.

**Closed by inferno-chromium** 2020-12-11 13:29 UTC
